AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  segment-personalize

  SAM Template for integrations between Segment and AWS Personalize

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  SegmentPersonalizeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: segment_personalize/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        SegmentPersonalize:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: post
      Environment:
          Variables:
            connections_source_write_key: your-segment-source-write-key
            personalize_tracking_id: your-personalize-tracker-id
            region_name: us-east-1
            endpoint_url: https://personalize-runtime.us-east-1.amazonaws.com
      Policies:
        - AWSLambdaExecute # Managed Policy
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:GetObjectACL
                - personalize:GetRecommendations
                - personalize:Record
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
